apiVersion: v1
kind: Service
metadata:
  name: celery-service
spec:
  selector:
    app: celery
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
